pitch_ground:
  source_limit: 5
  rows_limit: 100000000
  referral_codes:
  - pgdz-BpLnfgDs
  - pgdz-c3WD9F3q
  - pgdz-NfHK6a95
  - pgdz-jjJkwzDk
  - pgdz-h0h3fhfU
  - pgdz-VuS0jZ9u
  - pgdz-VbhV4vC6
  - pgdz-AWX40IVU
  - pgdz-WSP3NcHc
  - pgdz-iWvqZTa3
  - pgdz-N06RxRTZ
  - pgdz-HWUsaD7H
  - pgdz-Edz1ThbX
  - pgdz-fQ7pYSQ4
  - pgdz-n378l2VQ
  - pgdz-KGNbSuJE
  - pgdz-0fQbzONJ
  - pgdz-AAwdCxmM
  - pgdz-9BIabKER
  - pgdz-sUhPNmMm
  - pgdz-df3eSJyY
  - pgdz-tqwcFiUI
  - pgdz-LzXv3fcN
  - pgdz-IrWO8sTo
  - pgdz-FgoilA1U
  - pgdz-2WxNeW2g
  - pgdz-dgUVDsEW
  - pgdz-J88aX8tL
  - pgdz-FJ95qYU7
  - pgdz-UrN9ctec
  - pgdz-wZt6S5zj
  - pgdz-hD1tXRTm
  - pgdz-kYKQoN02
  - pgdz-FmWnQSK3
  - pgdz-wRC6UHK3
  - pgdz-KqAtxjP3
  - pgdz-ZmD2jtt4
  - pgdz-zgr6MeUj
  - pgdz-oAjcO0az
  - pgdz-MmtU4Ytv
  - pgdz-1P8OPmmS
  - pgdz-Na98d7ts
  - pgdz-taxy6nac
  - pgdz-nJBSuFpO
  - pgdz-hyIXE7PJ
  - pgdz-1DhUkLXq
  - pgdz-YYnENunq
  - pgdz-dswpTw5U
  - pgdz-DGDS34mS
  - pgdz-PYK8vmub
  - pgdz-3X9uXIu7
  - pgdz-FNcJjARQ
  - pgdz-T3RVhVrt
  - pgdz-24P7i6xC
  - pgdz-rL6Fc4Gc
  - pgdz-uHC14kau
  - pgdz-nATUPRHj
  - pgdz-GmuVmxHs
  - pgdz-yzzBbyOo
  - pgdz-nqVUSDK1
  - pgdz-V7fFMTuP
  - pgdz-CdWp0Qfu
  - pgdz-WWig4e6g
  - pgdz-XH83r9NE
  - pgdz-lCnqsGwV
  - pgdz-qyTeCtdR
  - pgdz-lF39hLZ5
  - pgdz-ZS7U0NlU
  - pgdz-A0Wq9J69
  - pgdz-ONeDbgGb
  - pgdz-V8RejsGN
  - pgdz-hi4E7olI
  - pgdz-d0IL3Ghx
  - pgdz-8sSGGHgm
  - pgdz-KwUMoa6S
  - pgdz-5VZlr0bU
  - pgdz-F3lCCzFc
  - pgdz-59bzlmW4
  - pgdz-SN0DXA1Y
  - pgdz-SyNBiOW5
  - pgdz-q5RsMQd9
  - pgdz-JWsEdQQN
  - pgdz-VIrudsYL
  - pgdz-DARHEe6g
  - pgdz-RFQKuuIB
  - pgdz-Q222rhts
  - pgdz-NPHcD2LZ
  - pgdz-eKlNxeCZ
  - pgdz-GRBPLcOL
  - pgdz-QrUoGHen
  - pgdz-mjv4Lyvf
  - pgdz-NknddV3H
  - pgdz-vcAYeM8c
  - pgdz-OIrni5gJ
  - pgdz-pu5hfeAM
  - pgdz-yJTxCL1g
  - pgdz-yMZ1Ps2o
  - pgdz-xjHAa0Go
  - pgdz-49Vfwuk4
  - pgdz-dacQvlFJ
  - pgdz-YxLdx9wQ
  - pgdz-QmuaHYTo
  - pgdz-YjSqIDwF
  - pgdz-4JM2AuR0
  - pgdz-KTZ715oo
  - pgdz-5Vh6V0oG
  - pgdz-vx3pGsPo
  - pgdz-2YJFmnSr
  - pgdz-0ld7qoZB
  - pgdz-3R7D4Z2y
  - pgdz-z7W78dpd
  - pgdz-tvrwH2dM
  - pgdz-glEhXguo
  - pgdz-68rqF2Ya
  - pgdz-ty5uqMgN
  - pgdz-l2Hjqu0G
  - pgdz-rQn5GqbA
  - pgdz-LAxSBXwm
  - pgdz-ee4KXtuV
  - pgdz-0fHjxGUz
  - pgdz-RmC09gAz
  - pgdz-sjtwpkvp
  - pgdz-MRkd8YqS
  - pgdz-5bFCLBsF
  - pgdz-TO3oWWe9
  - pgdz-4nfGnxUS
  - pgdz-uuvlvzGB
  - pgdz-NRiyOYI1
  - pgdz-z8dc3vvq
  - pgdz-FbEZsXci
  - pgdz-Rtf2Ulsm
  - pgdz-TY8AL0uR
  - pgdz-OLSyW2CP
  - pgdz-fyWmc4B4
  - pgdz-9oWLCblI
  - pgdz-6B8cDgOD
  - pgdz-j5Ou03jY
  - pgdz-HQZLGDNB
  - pgdz-WTZTaT00
  - pgdz-VZNw2yEA
  - pgdz-8JNkV2d5
  - pgdz-NK1aWq62
  - pgdz-U2jkGdgN
  - pgdz-iYC6fcJq
  - pgdz-ymmVG403
  - pgdz-QvWsAe3W
  - pgdz-HWoMzrTC
  - pgdz-xYCoCPxZ
  - pgdz-02aX1v9d
  - pgdz-74ycPwFJ
  - pgdz-4atA4A05
  - pgdz-lyLMSDG3
  - pgdz-fqFu8qwn
  - pgdz-TaFTwhAC
  - pgdz-cOOqAX6h
  - pgdz-V6JB9bdK
  - pgdz-iuaWUaX1
  - pgdz-DkFIircd
  - pgdz-e097EKxG
  - pgdz-zKTJLjCC
  - pgdz-n05QE41n
  - pgdz-sEGzF6gm
  - pgdz-F70E2BlA
  - pgdz-1PP25TLI
  - pgdz-Yh8R2zV0
  - pgdz-DCdE7PnE
  - pgdz-29EsVg7g
  - pgdz-ZqzY93yX
  - pgdz-4wb2lxcY
  - pgdz-gkOe6IN5
  - pgdz-XebSzyDF
  - pgdz-woepnxKb
  - pgdz-eLIFb37v
  - pgdz-itqMvvLw
  - pgdz-yTM8D5Uf
  - pgdz-6OpmmrXS
  - pgdz-mu6Gh4UW
  - pgdz-XAZ9UWrw
  - pgdz-zgCUn1w4
  - pgdz-BrlnKhdD
  - pgdz-GxScHLGM
  - pgdz-nCSllRkT
  - pgdz-m3hHfEKY
  - pgdz-ZExIpxNE
  - pgdz-V76HMQZ3
  - pgdz-Lh1DAI37
  - pgdz-Y1mAxluN
  - pgdz-G0ucKxRE
  - pgdz-MEWzvTcZ
  - pgdz-fckdrUax
  - pgdz-0cMpx1O7
  - pgdz-RbtV2hXu
  - pgdz-Up2DnEa8
  - pgdz-7Vrkv7vF
  - pgdz-FfHQ8ZNX
  - pgdz-qXO25nuY
  - pgdz-w659LqZD
  - pgdz-Ii05ao8o
  - pgdz-o9k4DifN
  - pgdz-975O4ok6
  - pgdz-jTmqcXfZ
  - pgdz-s3XMkRKQ
  - pgdz-fpIwoSYQ
  - pgdz-DnIr3Cwc
  - pgdz-ZZf3dUM0
  - pgdz-H1evbnDp
  - pgdz-vjAqOtcO
  - pgdz-jeS2LNdq
  - pgdz-8fgwY5JZ
  - pgdz-BQ2rdOjV
  - pgdz-706vGszN
  - pgdz-mVBqcxqA
  - pgdz-qezALuP2
  - pgdz-Hp3PPnHY
  - pgdz-lueRWGKq
  - pgdz-CZWHKOhi
  - pgdz-qXa1whyl
  - pgdz-wQEjXjow
  - pgdz-u5fBKSu7
  - pgdz-Pcb4F8Zo
  - pgdz-j0MQrvd0
  - pgdz-9ssUeCkp
  - pgdz-qYhjRdjx
  - pgdz-MHoMROK8
  - pgdz-p01CKw3J
  - pgdz-1eb0iwRO
  - pgdz-scPU5kzj
  - pgdz-uFy9O3WB
  - pgdz-W9AD8scx
  - pgdz-YVH98sQw
  - pgdz-BamvWFyL
  - pgdz-xhK95dYg
  - pgdz-GmV35r9J
  - pgdz-YDDa57qm
  - pgdz-3fPPYAtC
  - pgdz-ybCxTLiY
  - pgdz-Oa6cqd4f
  - pgdz-i0Kcm8O2
  - pgdz-8Zu5sojB
  - pgdz-NmQ9fNUs
  - pgdz-uqZqNArD
  - pgdz-glJOEYi5
  - pgdz-nzw2DUaw
  - pgdz-eYFXjBzd
  - pgdz-i8YhTIgF
  - pgdz-VYXwYPpc
  - pgdz-DqWWWe1a
  - pgdz-gMCdanpL
  - pgdz-xRXfHR2R
  - pgdz-JQBi4kaG
  - pgdz-23VCThks
  - pgdz-ZM1OzK2B
  - pgdz-QnzmtsFi
  - pgdz-wE9TQVtm
  - pgdz-vKRXHMmF
  - pgdz-qhD21i5O
  - pgdz-K82OUnNv
  - pgdz-XsRyu3vU
  - pgdz-XuE47jkS
  - pgdz-blLouUYA
  - pgdz-JnJrBRa0
  - pgdz-pi7YHEYJ
  - pgdz-s8xVOr6J
  - pgdz-xgWfuPWq
  - pgdz-2nAFdWsB
  - pgdz-NFjZS3AV
  - pgdz-hjChTHlO
  - pgdz-IgmuiPob
  - pgdz-CUJ1kXwo
  - pgdz-nOmWtfhN
  - pgdz-3mR2252k
  - pgdz-4VZFqFTb
  - pgdz-V3W5liQR
  - pgdz-KMfQmd29
  - pgdz-oDksyTcp
  - pgdz-AbYC4NRq
  - pgdz-NAOzPGIs
  - pgdz-p1BOFUiE
  - pgdz-sOraXGmJ
  - pgdz-RugOZlRf
  - pgdz-2Gi1Fzcx
  - pgdz-2k8ErECI
  - pgdz-TW9CxKv0
  - pgdz-VpHdW7y6
  - pgdz-K6pHxs6M
  - pgdz-9O44qIuV
  - pgdz-yJH4DQ7P
  - pgdz-2YVag7kK
  - pgdz-oSashlEU
  - pgdz-SiXiey5d
  - pgdz-9POMitEd
  - pgdz-kKZpdAaK
  - pgdz-IYj19tuH
  - pgdz-zEtyyJei
  - pgdz-sONkaUNP
  - pgdz-bqcAVuS7
  - pgdz-I3OPeSo3
  - pgdz-2N2ZGD3b
  - pgdz-f7uhGnj5
  - pgdz-71g1Dq1O
  - pgdz-T6MaELea
  - pgdz-QJfsQXuH
  - pgdz-bhCBaH8O
  - pgdz-TJMYOgF5
  - pgdz-KqNOk3pN
  - pgdz-5ySWX63k
  - pgdz-a6mIxHTd
  - pgdz-WiJ9T0hy
  - pgdz-l9vcIus1
  - pgdz-R5cSxk1K
  - pgdz-vreDX798
  - pgdz-uPnjpNGU
  - pgdz-DmRIeRLv
  - pgdz-HrvrLBaP
  - pgdz-4kBzdOZP
  - pgdz-IFiahbUV
  - pgdz-XJcM1OcC
  - pgdz-js3c131L
  - pgdz-t7WQsvN0
  - pgdz-BCCbtQLA
  - pgdz-QmPoBHkR
  - pgdz-EPiHQu0N
  - pgdz-1bFVx7lK
  - pgdz-wlkXwr9s
  - pgdz-VUSkt9bb
  - pgdz-TKSTzb7Z
  - pgdz-Arp36jLk
  - pgdz-hniT7p9T
  - pgdz-uSZ7CD3a
  - pgdz-h0aQmdHb
  - pgdz-GqNjrrlF
  - pgdz-9vEP7yhC
  - pgdz-78KftjG6
  - pgdz-lNpyQXbO
  - pgdz-7oWHkNug
  - pgdz-lrYyaFn3
  - pgdz-SLx5j0Hl
  - pgdz-WQykrBQV
  - pgdz-Z70s5gBL
  - pgdz-UOBdzKmR
  - pgdz-vBAptQ7v
  - pgdz-G68s2iVm
  - pgdz-HLffJT0Y
  - pgdz-82oiyKjq
  - pgdz-u4hoohlk
  - pgdz-JEzEpxpw
  - pgdz-7ieHA4ZC
  - pgdz-gvXKWvBW
  - pgdz-HPcKHTtz
  - pgdz-sOltb700
  - pgdz-o81Au43C
  - pgdz-B8TUOHjE
  - pgdz-b9tzm1O1
  - pgdz-11g8Vzj3
  - pgdz-f9nAULf2
  - pgdz-aKt6SvyY
  - pgdz-j8Zbjyra
  - pgdz-UuOzpXYQ
  - pgdz-fUmgUP7U
  - pgdz-prNCPY6F
  - pgdz-SOYKj1TI
  - pgdz-Wbhxqr0u
  - pgdz-t2LqMwjT
  - pgdz-W39eNwOW
  - pgdz-SFJVvVc3
  - pgdz-LVCHc2Ce
  - pgdz-hLHRxVmR
  - pgdz-Fa4sYQxH
  - pgdz-BfcVYCiR
  - pgdz-IDPk8dLG
  - pgdz-GvTwOXOG
  - pgdz-BXhiE8xn
  - pgdz-LBMe9j8r
  - pgdz-mJE6GsJr
  - pgdz-OQG8ABJ4
  - pgdz-jMUzGRUD
  - pgdz-hiMKPOUN
  - pgdz-wak44Rfj
  - pgdz-wXugWmW6
  - pgdz-UmreJUpY
  - pgdz-MIVozOHT
  - pgdz-YYgLFNGA
  - pgdz-STmAgoUg
  - pgdz-H2K4rjti
  - pgdz-8KayVLUJ
  - pgdz-uBPh3EgC
  - pgdz-TfBhwjV8
  - pgdz-Gc0uIqkK
  - pgdz-eXEpiu7L
  - pgdz-ju25vR9p
  - pgdz-7Iw1O9dZ
  - pgdz-G1tVA0IL
  - pgdz-nhudTWhf
  - pgdz-disBvEAp
  - pgdz-AFve7WYk
  - pgdz-apbAb1RQ
  - pgdz-H7eaYUcL
  - pgdz-w6yMxK8C
  - pgdz-Voq6PGuz
  - pgdz-dWJWXajl
  - pgdz-Y1V2NwX7
  - pgdz-rlRrsTDY
  - pgdz-ZQ673AKq
  - pgdz-6PmKA5W5
  - pgdz-muqj1EVU
  - pgdz-EADrl083
  - pgdz-DpL2wiM7
  - pgdz-LRmAuLTG
  - pgdz-nnT1e8wU
  - pgdz-Hz0AmIuQ
  - pgdz-R5NUl8S4
  - pgdz-5kzjyfJX
  - pgdz-UUQDfrvI
  - pgdz-JgwIDpGe
  - pgdz-UMYPs2pp
  - pgdz-yqZFjPt2
  - pgdz-2h7EhdHr
  - pgdz-aDhBcbtY
  - pgdz-UbNIfSAP
  - pgdz-BHKcP0SA
  - pgdz-w2sQnHuv
  - pgdz-A7HpRYNh
  - pgdz-Ths3j7Ub
  - pgdz-755MoXEE
  - pgdz-40h5J9wu
  - pgdz-BQivQy7V
  - pgdz-IdGP6MnG
  - pgdz-aX378C8z
  - pgdz-nT4G6LNN
  - pgdz-bekUZiSX
  - pgdz-OSxZM5Mb
  - pgdz-lPZf9Txf
  - pgdz-zIozt8Fe
  - pgdz-RRmYKLOm
  - pgdz-406EEKha
  - pgdz-m3Nvfopm
  - pgdz-ALrfVL0x
  - pgdz-qacB2zod
  - pgdz-WVK1E8oG
  - pgdz-MDCfLXVQ
  - pgdz-xa95Lyao
  - pgdz-PdmorUQ1
  - pgdz-fS3gLrMZ
  - pgdz-TzQYfIgV
  - pgdz-USNCnuPr
  - pgdz-xIsun9Jd
  - pgdz-hBgtpRYX
  - pgdz-uPoZEZAh
  - pgdz-GuRXXogC
  - pgdz-W4mtWR68
  - pgdz-Fyex6O8R
  - pgdz-3U3OhUEB
  - pgdz-8uLskZwW
  - pgdz-OJABTUjf
  - pgdz-mQ6d20Ad
  - pgdz-GR9g88Mn
  - pgdz-NEvSGOQJ
  - pgdz-YaDypUmk
  - pgdz-lexohuc4
  - pgdz-jcJzC0H3
  - pgdz-vGzpqPjI
  - pgdz-9Q3Uzd4Q
  - pgdz-DNZpPPIh
  - pgdz-Q0zTb0TV
  - pgdz-Ih7DhHFT
  - pgdz-vbIlX69u
  - pgdz-NWy3wvUc
  - pgdz-3aBLWgm3
  - pgdz-uobPpJNj
  - pgdz-jEr81FDN
  - pgdz-QWQn2KU9
  - pgdz-MrzerJdU
  - pgdz-0YUxLHII
  - pgdz-A0fZNJqE
  - pgdz-5M6Oz7Vc
  - pgdz-9p10nB7D
  - pgdz-PZKGBwl2
  - pgdz-bBQ0GJw4
  - pgdz-AQPE2XKI
  - pgdz-7IjTm03W
  - pgdz-yxL5X0Ct
  - pgdz-lX6yWBR4
  - pgdz-vhmc4zkR
  - pgdz-h0tE6Fng
  - pgdz-jpmispzD
  - pgdz-h2lfkBBj
  - pgdz-tIfVq4Ro
  - pgdz-5bRXHsI2
  - pgdz-Z1iaumG9
  - pgdz-j4oAtBau
  - pgdz-1CiMHU3c
  - pgdz-XNGNeIKd
  - pgdz-siICpOKc
  - pgdz-vrBJyVYq
  - pgdz-58fF7OtK
  - pgdz-eGQHUhCp
  - pgdz-HWrdV999
  - pgdz-clmeGMeC
  - pgdz-320ez3IA
  - pgdz-OoNW8pzZ
